### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/farmsim.ts#2]
- [x] turn everything async with promises
- [x] Add contributors
- [x] Commands: 
  - [x] init
  - [x] info
  - [x] verify
    - [x] XML format
    - [x] LUA
    - [ ] modDesc contents
    - [ ] translations
  - [x] uninstall
  - [x] add config
  - [x] log
  - [x] install
  - [x] run
  - [x] build
    - [x] force CDATA? ***required to make simple mods pass QA***
    - [x] templating ***required to make seasons work***
    - [x] Add console support (_console version) ***required for seasons and updates***
- [ ] MP
- [ ] translations
- [x] Replace any log stuff with winston logger

### Verify
Check validity of XML files
Check if LUA files pass through the bytecode compiler of LuaJIT

### Translations

Read EN file with formatting
Read other languages
Write any other language file with formatting

### Config
`fs config set debug=true`
`fs config get debug`
